name: bd_poc

on: 
  workflow_dispatch:
#   schedule:
#     - cron: "5 * * * *"

env:
     bd-project: Test4
     version: python_bd_scan_v1

jobs:
  build-scan:
    runs-on: [ road-runner ]
   
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run python
        run : |
               python application.py
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
    
      - name: bd poc scan
        run: bash <(curl -s https://detect.synopsys.com/detect9.sh) 
           --blackduck.url=https://mercedes-benz-poc.app.blackduck.com/
           --blackduck.api.token="${{secrets.BD_POC_TOKEN}}"
           --detect.project.name="${{ env.bd-project}}"
           --detect.project.version.name="${{env.version}}"
           --detect.code.location.name="${{ env.bd-project}}"-"${{env.version}}"
           --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
           --detect.blackduck.signature.scanner.upload.source.mode=true
 
