name: IT-PROD

on: 
  workflow_dispatch:
#   schedule:
#     - cron: "5 * * * *"

env:
     bd-project: Shetrak_bd_scan
     version: bd_scan_python
     bd-url: "https://bdscan.i.mercedes-benz.com"

jobs:
  build-scan:
    runs-on: [ small ]
   
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
#       - name: run python
#         run : |
#                python application.py
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
    
      - name: IT - PROD
        run: bash <(curl -s https://detect.synopsys.com/detect9.sh) 
           --blackduck.url=https://bdscan.i.mercedes-benz.com/
           --blackduck.api.token="${{secrets.BD_IT_PROD_TOKEN}}"
           --detect.project.name="${{ env.bd-project}}"
           --detect.project.version.name="${{env.version}}"
           --detect.code.location.name="${{ env.bd-project}}"-"${{env.version}}"
           --detect.blackduck.signature.scanner.arguments='--min-scan-interval=0'
           
