name: IT-PROD

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "39 06 * * *"
    
#   schedule:
#     - cron: "5 * * * *"

env:
     bd-project: "Blackduck-May29-Demo"
     # bd-project: "Blackduck-Jul31-Demo"
     bd-url: "https://mercedes-benz.app.blackduck.com/"

jobs:
  build-scan:
    runs-on: [ medium ]
   
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
#       - name: run python
#         run : |
#                python application.py
               
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          

     
          
      - name: IT - PROD
        run: bash <(curl -s https://detect.blackduck.com/detect10.sh) 
           --blackduck.url="https://mercedes-benz.app.blackduck.com/"
           --blackduck.api.token="${{secrets.BD_IT_PROD_TOKEN}}"
           --detect.project.name="${{ env.bd-project}}"
           --detect.project.version.name="Python-test"
           --detect.code.location.name="${{ env.bd-project}}-testdate"
           --detect.excluded.detector.types=GIT
           
