name: IT-Prod


on: 
  workflow_dispatch:
  
## Please change the project name to your Blackdcuk project here
# env:
#      bd-project: GHA-BD-Scan-Test
#      version: Python--version1

jobs:
  build-scan:
    runs-on: [ road-runner ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run python
        run : |
               python application.py
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
    
      - name: blackduck scan
        run: |
          echo "Branch name provided in input = ${{ github.ref }}"
          if [ "${{ github.ref }}" != *"main"* ]; then
               echo "main branch selected"
               SCAN_MODE="INTELLIGENT"
               echo "SCAN_MODE=$SCAN_MODE" >> $GITHUB_ENV
          fi
          echo "Scan mode selected $SCAN_MODE"
          echo "bd-scan starts"
          bash < (curl -s https://detect.synopsys.com/detect8.sh)
          --blackduck.url="https://bdscan.i.mercedes-benz.com/"
          --blackduck.trust.cert=true
          --blackduck.api.token="${{ secrets.BD_IT_PROD_TOKEN }}"
          --blackduck.timeout="1800"
          --detect.project.name="${{ secrets.BD_PROJ_NAME }}"
          --detect.project.version.name="test"
          --detect.blackduck.scan.mode="${{env.SCAN_MODE}}"
          --detect.source.path="$PROJECT_DIR"
           




           
           
#            --detect.project.name="${{ env.bd-project}}"
#            --detect.project.version.name="${{env.version}}"
#            --detect.code.location.name="${{ env.bd-project}}"-"${{env.version}}"
           
#       - name: blackduck scan
#         run: bash <(curl -s https://detect.synopsys.com/detect8.sh) 
#            --blackduck.url=https://bdscan.i.mercedes-benz.com/
#            --blackduck.api.token="${{secrets.BLACKDUCK_API_TOKEN}}"
#            --detect.project.name="${{ env.bd-project}}"
#            --detect.project.version.name="${{env.version}}"
#            --detect.code.location.name="${{ env.bd-project}}"-"${{env.version}}"
#            --detect.python.path=
#            --detect.pip.path=
#            --detect.pipfile.dependency.types.excluded=NONE,DEV 
#            --detect.pip.requirements.path
#            --detect.pipenv.path=""
#            --detect.pip.project.name
#            --detect.pip.project.version.name=
           
          
 
