name: IT-PROD

on: 
  workflow_dispatch:
#   schedule:
#     - cron: "5 * * * *"

env:
     # bd-project: "Shetrak-bd-scan"
     bd-project: "Threatix-test"
     # version: bd_scan_python_2
     # bd-url: "https://bdscan.i.mercedes-benz.com"
     bd-url: "https://mercedes-benz.app.blackduck.com/"

jobs:
  build-scan:
    runs-on: [ medium ]
   
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
#       - name: run python
#         run : |
#                python application.py
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.16.1'
          distribution: 'corretto'

      - name: Java version
        run: java --version
      
      # - name: Black Duck SCA Scan
      #   uses: blackduck-inc/black-duck-security-scan@v2.0.0
      #   env:
      #       DETECT_PROJECT_NAME: Shetrak_bd_scan
      #       DETECT_PROJECT_VERSION_NAME: "bd_scan_python_2"
      #   with:
      #     blackducksca_url: https://bdscan.i.mercedes-benz.com
      #     blackducksca_token: ${{ secrets.BD_IT_PROD_TOKEN }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     blackducksca_scan_full: true
      #     blackducksca_scan_failure_severities: ALL
      #     detect_args: '--detect.diagnostic=true'
          
      - name: IT - PROD
        run: bash <(curl -s https://detect.blackduck.com/detect10.sh) 
           --blackduck.url="https://mercedes-benz.app.blackduck.com/"
           --blackduck.api.token="${{secrets.BD_IT_PROD_TOKEN1}}"
           --detect.project.name="${{ env.bd-project}}"
           --detect.project.version.name="Python-test3"
           --detect.code.location.name="${{ env.bd-project}}"
           --detect.blackduck.signature.scanner.arguments='--min-scan-interval=0'
           
