name: Create PR to GitHub.com

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch

jobs:
  create_pr:
    runs-on: [ small ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is available

      #Git commit credentials     
      - name: Get Git user ID and email
        run: |
          git_user_id=$(git log -1 --pretty=format:'%an')
          git_user_email=$(git log -1 --pretty=format:'%ae')
          echo "GIT_USER_ID=$git_user_id" >> $GITHUB_ENV
          echo "GIT_USER_EMAIL=$git_user_email" >> $GITHUB_ENV

    # Download the build folder     
   
   
   #configure git    
      - name: Configure Git
        run: |
          git config --global user.name '${{ env.GIT_USER_ID }}"'
          git config --global user.email '${{ env.GIT_USER_EMAIL }}'

      - name: Push to GitHub.com
        run: |
          git remote add github_com "https://${{ secrets.GITCOM_SECRET }}@github.com/Rakshitha569/Test-new.git"
          git push github_com main:main -f 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITCOM_SECRET }}
          branch: test
          base: main
          title: 'Sync from Git Enterprise'
          body: 'This PR syncs changes from the Git Enterprise main branch.'
