name: RD-scan-INT
on: 
  workflow_dispatch:
  
env:
     detect: https://detect.synopsys.com/detect9.sh
     bd-url: https://bdscan-rd-int.i.mercedes-benz.com/ 
     bd-token: ${{secrets.BD_RD_INT_SCAN}}
     bd-project: test-shetrak
     version: PYTHON--Version1
     cl: after-upgrade-2024.4.0
     OPTION :  --detect.timeout=1800 --blackduck.timeout="300" --detect.policy.check.fail.on.severities=ALL --detect.report.timeout="200000" --detect.notices.report=true 


jobs:
  #Python
  python-build-scan:
    runs-on: [ road-runner ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
    
      - name: bd scan
        run: bash <(curl -s ${{env.detect}} ) 
           --blackduck.url="${{env.bd-url}}"
           --blackduck.api.token="${{env.bd-token}}"
           --detect.code.location.name="${{env.cl}}"python-code-location
           ${{env.OPTION}}
           --detect.project.name="${{env.bd-project}}"
           --detect.project.version.name=PYTHON"${{env.version}}"
          
